export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const technologies = {
  frontEnd: [
    "HTML",
    "CSS",
    "SCSS",
    "Tailwind CSS",
    "Material UI",
    "Ant Design",
    "JavaScript",
    "TypeScript",
    "jQuery",
    "React",
    "React Native",
    "Redux",
    "Next.js",
    "Astro",
    "Vite",
    "Handlebars",
    "Electron",
    "Flutter",
    "D3",
    "Highcharts",
    "Vue.js", // Added Vue.js
    "Web Components", // Added Web Components
    "Axios", // Added Axios
  ],
  backEnd: [
    "Node.js",
    "Bun",
    "Express",
    "Java",
    "Spring Boot",
    "Kotlin",
    "Hibernate",
    "Prisma",
    "Supabase",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "GraphQL",
    "Elasticsearch",
    "Microservices",
    "RESTful API", 
    "OAuth 2.0", 
    "Docker Compose", 
  ],
  cloudAndDeployment: [
    "Google Cloud",
    "Docker",
    "npm",
    "Maven",
    "Jenkins",
    "TeamCity",
    "Git",
    "GitHub",
    "Bitbucket",
    "Webpack",
    "DigitalOcean", 
    "Vercel",
    "Kubernetes (k8s)", 
    "CI/CD", 
  ],
  additionalSkills: [
    "Test-Driven Development (TDD)",
    "Okta",
    "JWT",
    "WordPress",
    "Stripe",
    "Agile Methodologies (Scrum)",
    "Figma",
    "Sketch",
    "SOLID",
    "DRY",
    "Agile",
    "Composable architecture", 
  ],
};


export const TimeLineData = [
  { year: 2009, text: 'Supporting a team of civil engineers in GIS, IT and Web services', },
  { year: 2010, text: 'Side hustles as a freelance developer for various clients', },
  { year: 2016, text: 'Growing into a full-stack developer while working on enterprise software', },
  { year: 2023, text: 'Started indie hacking, building e-commerce stores and building own software', },
  { year: 2024, text: 'Working on multiple SaaS & E-commerce platforms', },
];
