export const projects = [
  {
    title: 'LinkTracker',
    description: 'A platform to organize, track, and analyze the performance of shared links.',
    image: '/images/linktracker.png',
    tags: ['SaaS', 'Link Management'],
    visit: 'https://linktracker.info',
    id: 0,
  },
  {
    title: 'hashion',
    description: 'Turn your Hashnode blog into a Notion database and manage it with everything else.',
    image: '/images/hashion.png',
    tags: ['Blogging', 'Notion', 'Hashnode'],
    visit: 'https://hashion.link',
    id: 1,
  },
  {
    title: 'LustigeDruckShirts',
    description: 'A Print-On-Demand shop for humorous T-shirts and bags in the German market.',
    image: '/images/lustigedruckshirts.png',
    tags: ['Print-On-Demand', 'E-commerce'],
    visit: 'https://lustigedruckshirts.de',
    id: 2,
  },
  {
    title: 'Reise Prints',
    description: 'A Print-On-Demand shop for travel-related products in the German market.',
    image: '/images/reiseprints.png',
    tags: ['Print-On-Demand', 'Travel'],
    visit: 'https://reiseprints.de',
    id: 3,
  },
  {
    title: 'Hunde & Katzen Druck',
    description: 'A Print-On-Demand shop for dog and cat lovers in the German market.',
    image: '/images/hundekatzendruck.png',
    tags: ['Print-On-Demand', 'E-commerce'],
    visit: 'https://hundekatzendruck.de',
    id: 4,
  },
  {
    title: 'Retro Heim & Leben',
    description: 'A Print-On-Demand shop for retro-style home and decorations in the German market.',
    image: '/images/retroheimundleben.png',
    tags: ['Print-On-Demand', 'Home Decor'],
    visit: 'https://retroheimundleben.de',
    id: 5,
  },
  {
    title: 'Personalisierte Babykleidung',
    description: 'A Print-On-Demand shop for baby products in the German market.',
    image: '/images/personalisiertebabykleidung.png',
    tags: ['Print-On-Demand', 'Baby Products'],
    visit: 'https://personalisiertebabykleidung.de',
    id: 6,
  },
  {
    title: 'Notion Template (MDW)',
    description: 'A Notion template for Noah Kagan’s book "Million Dollar Weekend."',
    image: '/images/notion-template.png',
    tags: ['Notion', 'Templates'],
    visit: 'https://www.notion.so/templates/million-dollar-weekend-workbook',
    id: 7,
  },
  {
    title: 'Print2Social',
    description: 'An AI-powered social media manager for Print-On-Demand businesses.',
    image: '/images/print2social.png',
    tags: ['SaaS', 'Automation', 'Print-On-Demand'],
    visit: 'https://print2social.com',
    id: 8,
  },
  {
    title: 'Lustige Sprüche',
    description: 'A niche German website with funny slogans and jokes that drives traffic to other ventures.',
    image: '/images/lustigesprueche.png',
    tags: ['SEO', 'Blogging', 'Humor'],
    visit: 'https://lustigesprueche.online',
    id: 9,
  },
  {
    title: 'WebCrawler',
    description: 'A web crawler to gather external links from any page or entire domain.',
    image: '/images/webcrawler.png',
    tags: ['Web Crawling', 'Link Building'],
    visit: 'https://crawler.samiralibabic.com',
    id: 10,
  },
  {
    title: 'Affiliate Companies',
    description: 'Discover the top affiliate programs with excellent earning potential.',
    image: '/images/affiliatecompanies.png',
    tags: ['Affiliate Marketing', 'Directory'],
    visit: 'https://affiliatecompanies.net',
    id: 11,
  },
  {
    title: 'Print On Demand Business',
    description: 'A comprehensive directory of suppliers for your print-on-demand businesses.',
    image: '/images/printondemandbusiness.png',
    tags: ['Print-On-Demand', 'Directory'],
    visit: 'https://printondemandbusiness.com',
    id: 12,
  }
];


export const technologies = {
  frontEnd: [
    "HTML",
    "CSS",
    "SCSS",
    "Tailwind CSS",
    "Material UI",
    "Ant Design",
    "JavaScript",
    "TypeScript",
    "jQuery",
    "React",
    "React Native",
    "Redux",
    "Next.js",
    "Astro",
    "Vite",
    "Handlebars",
    "Electron",
    "Flutter",
    "D3",
    "Highcharts",
    "Vue.js", 
    "Web Components", 
    "Axios", 
  ],
  backEnd: [
    "Node.js",
    "Bun",
    "Express",
    "Java",
    "Spring Boot",
    "Kotlin",
    "Hibernate",
    "Prisma",
    "Supabase",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "GraphQL",
    "Elasticsearch",
    "Microservices",
    "RESTful API", 
    "OAuth 2.0", 
    "Docker Compose", 
  ],
  devOps: [
    "Google Cloud",
    "Docker",
    "npm",
    "Maven",
    "Jenkins",
    "TeamCity",
    "Git",
    "GitHub",
    "Bitbucket",
    "Webpack",
    "DigitalOcean", 
    "Vercel",
    "Kubernetes (k8s)", 
    "CI/CD", 
  ],
  additionalSkills: [
    "Test-Driven Development (TDD)",
    "Okta",
    "JWT",
    "WordPress",
    "Stripe",
    "Agile Methodologies (Scrum)",
    "Figma",
    "Sketch",
    "SOLID",
    "DRY",
    "Agile",
    "Composable architecture", 
  ],
};


export const TimeLineData = [
  { year: 2009, text: 'Supporting a team of civil engineers in GIS, IT and Web services', },
  { year: 2010, text: 'Side hustles as a freelance developer for various clients', },
  { year: 2016, text: 'Growing into a full-stack developer while working on enterprise software', },
  { year: 2023, text: 'Started indie hacking, building e-commerce stores and building own software', },
  { year: 2024, text: 'Working on multiple SaaS & E-commerce platforms', },
];
